<!DOCTYPE html>
<html
  xmlns="http://www.w3.org/1999/xhtml"
  xmlns:v="urn:schemas-microsoft-com:vml"
  xmlns:o="urn:schemas-microsoft-com:office:office"
>
  <head>
    <title> </title>
    <!--[if !mso]><!-->
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!--<![endif]-->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style type="text/css">
      #outlook a {
        padding: 0;
      }

      body {
        margin: 0;
        padding: 0;
        -webkit-text-size-adjust: 100%;
        -ms-text-size-adjust: 100%;
      }

      table,
      td {
        border-collapse: collapse;
        mso-table-lspace: 0pt;
        mso-table-rspace: 0pt;
      }

      img {
        border: 0;
        height: auto;
        line-height: 100%;
        outline: none;
        text-decoration: none;
        -ms-interpolation-mode: bicubic;
      }

      p {
        display: block;
        margin: 13px 0;
      }
    </style>
    <!--[if mso]>
      <xml>
        <o:OfficeDocumentSettings>
          <o:AllowPNG />
          <o:PixelsPerInch>96</o:PixelsPerInch>
        </o:OfficeDocumentSettings>
      </xml>
    <![endif]-->
    <!--[if lte mso 11]>
      <style type="text/css">
        .mj-outlook-group-fix {
          width: 100% !important;
        }
      </style>
    <![endif]-->
    <!--[if !mso]><!-->
    <link
      href="https://fonts.googleapis.com/css?family=Merriweather:normal,italic,bold&display=swap"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Playfair+Display:normal,italic,bold&display=swap"
      rel="stylesheet"
      type="text/css"
    />
    <style type="text/css">
      @import url(https://fonts.googleapis.com/css?family=Merriweather:normal,italic,bold&display=swap);
      @import url(https://fonts.googleapis.com/css?family=Playfair+Display:normal,italic,bold&display=swap);
    </style>
    <!--<![endif]-->
    <style type="text/css">
      @media only screen and (min-width: 480px) {
        .mj-column-per-100 {
          width: 100% !important;
          max-width: 100%;
        }

        .mj-column-per-50 {
          width: 50% !important;
          max-width: 50%;
        }
      }
    </style>
    <style media="screen and (min-width:480px)">
      .moz-text-html .mj-column-per-100 {
        width: 100% !important;
        max-width: 100%;
      }

      .moz-text-html .mj-column-per-50 {
        width: 50% !important;
        max-width: 50%;
      }
    </style>
    <style type="text/css">
      @media only screen and (max-width: 480px) {
        table.mj-full-width-mobile {
          width: 100% !important;
        }

        td.mj-full-width-mobile {
          width: auto !important;
        }
      }
    </style>
    <style type="text/css">
      .vdt_styles {
      }

      .vdt_hide-on-desktop {
        display: none !important;
      }

      .vdt_hide-on-desktop table,
      .vdt_hide-on-desktop div,
      .vdt_hide-on-desktop p {
        mso-hide: all !important;
      }

      @media only screen and (max-width: 480px) {
        .vdt_hide-on-mobile {
          display: none !important;
        }

        .vdt_hide-on-desktop {
          display: block !important;
        }
      }
    </style>
  </head>

  <body style="word-spacing: normal; background-color: #d3c6a8">
    <div style="background-color: #d3c6a8">
      <!--[if mso | IE]><table align="center" border="0" cellpadding="0" cellspacing="0" class="" style="width:600px;" width="600" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
      <div
        style="
          background: #172b4d;
          background-color: #172b4d;
          margin: 0px auto;
          max-width: 600px;
        "
      >
        <table
          align="center"
          border="0"
          cellpadding="0"
          cellspacing="0"
          role="presentation"
          style="background: #172b4d; background-color: #172b4d; width: 100%"
        >
          <tbody>
            <tr>
              <td
                style="
                  direction: ltr;
                  font-size: 0px;
                  padding: 20px;
                  padding-bottom: 0px;
                  padding-left: 20px;
                  padding-right: 20px;
                  padding-top: 20px;
                  text-align: center;
                "
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:560px;" ><![endif]-->
                <div
                  class="mj-column-per-100 mj-outlook-group-fix"
                  style="
                    font-size: 0px;
                    text-align: left;
                    direction: ltr;
                    display: inline-block;
                    vertical-align: top;
                    width: 100%;
                  "
                >
                  <table
                    border="0"
                    cellpadding="0"
                    cellspacing="0"
                    role="presentation"
                    width="100%"
                  >
                    <tbody>
                      <tr>
                        <td style="vertical-align: top; padding: 0">
                          <table
                            border="0"
                            cellpadding="0"
                            cellspacing="0"
                            role="presentation"
                            style
                            width="100%"
                          >
                            <tbody>
                              <tr>
                                <td
                                  style="font-size: 0px; word-break: break-word"
                                >
                                  <div style="height: 10px; line-height: 10px">
                                    &#8202;
                                  </div>
                                </td>
                              </tr>
                              <tr>
                                <td
                                  align="center"
                                  style="
                                    font-size: 0px;
                                    padding: 10px;
                                    word-break: break-word;
                                  "
                                >
                                  <div
                                    style="
                                      font-family: 'Playfair Display', 'Georgia',
                                        'Times New Roman', serif;
                                      font-size: 40px;
                                      line-height: 1;
                                      text-align: center;
                                      color: #11cdef;
                                    "
                                  >
                                    <strong
                                      >voyage- Invitation d'inscription </strong
                                    >
                                  </div>
                                </td>
                              </tr>
                            </tbody>
                          </table>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
                <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <!--[if mso | IE]></td></tr></table><table align="center" border="0" cellpadding="0" cellspacing="0" class="" style="width:600px;" width="600" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
      <div
        style="
          background: #172b4d;
          background-color: #172b4d;
          margin: 0px auto;
          max-width: 600px;
        "
      >
        <table
          align="center"
          border="0"
          cellpadding="0"
          cellspacing="0"
          role="presentation"
          style="background: #172b4d; background-color: #172b4d; width: 100%"
        >
          <tbody>
            <tr>
              <td
                style="
                  direction: ltr;
                  font-size: 0px;
                  padding: 20px;
                  text-align: center;
                "
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:560px;" ><![endif]-->
                <div
                  class="mj-column-per-100 mj-outlook-group-fix"
                  style="
                    font-size: 0px;
                    text-align: left;
                    direction: ltr;
                    display: inline-block;
                    vertical-align: top;
                    width: 100%;
                  "
                >
                  <table
                    border="0"
                    cellpadding="0"
                    cellspacing="0"
                    role="presentation"
                    width="100%"
                  >
                    <tbody>
                      <tr>
                        <td style="vertical-align: top; padding: 0">
                          <table
                            border="0"
                            cellpadding="0"
                            cellspacing="0"
                            role="presentation"
                            style
                            width="100%"
                          >
                            <tbody>
                              <tr>
                                <td
                                  align="center"
                                  style="
                                    font-size: 0px;
                                    padding: 10px;
                                    word-break: break-word;
                                  "
                                >
                                  <table
                                    border="0"
                                    cellpadding="0"
                                    cellspacing="0"
                                    role="presentation"
                                    style="
                                      border-collapse: collapse;
                                      border-spacing: 0px;
                                    "
                                    class="mj-full-width-mobile"
                                  >
                                    <tbody>
                                      <tr>
                                        <td
                                          style="width: 540px"
                                          class="mj-full-width-mobile"
                                        >
                                          <img
                                            height="auto"
                                            src="https://img.freepik.com/free-vector/college-university-acceptance-letter-with-laptop-screen-open-envelope-document-email_503038-353.jpg"
                                            style="
                                              border: 0;
                                              border-radius: 8px;
                                              display: block;
                                              outline: none;
                                              text-decoration: none;
                                              height: auto;
                                              width: 100%;
                                              font-size: 13px;
                                            "
                                            width="540"
                                          />
                                        </td>
                                      </tr>
                                    </tbody>
                                  </table>
                                </td>
                              </tr>
                              <tr>
                                <td
                                  style="font-size: 0px; word-break: break-word"
                                >
                                  <div style="height: 40px; line-height: 40px">
                                    &#8202;
                                  </div>
                                </td>
                              </tr>

                              <tr>
                                <td
                                  align="center"
                                  style="
                                    font-size: 0px;
                                    padding: 10px;
                                    word-break: break-word;
                                  "
                                >
                                  <div
                                    style="
                                      font-family: 'Merriweather', 'Georgia',
                                        'Times New Roman', serif;
                                      font-size: 20px;
                                      line-height: 1.5;
                                      text-align: center;
                                      color: #11cdef;
                                    "
                                  >
                                    Bonjour monsieur ${nom} ${prenom} Votre entreprise vous a invité parmis nous! S'il vous plait de confirmer pour
                                    s'inscrire à voyage.
                                  </div>
                                </td>
                              </tr>
                              <tr>
                                <td
                                  style="font-size: 0px; word-break: break-word"
                                >
                                  <div style="height: 20px; line-height: 20px">
                                    &#8202;
                                  </div>
                                </td>
                              </tr>
                              <tr>
                                <td
                                  align="center"
                                  vertical-align="middle"
                                  style="
                                    font-size: 0px;
                                    padding: 0px;
                                    padding-top: 0px;
                                    padding-right: 10px;
                                    padding-bottom: 0px;
                                    padding-left: 10px;
                                    word-break: break-word;
                                  "
                                >
                                  <table
                                    border="0"
                                    cellpadding="0"
                                    cellspacing="0"
                                    role="presentation"
                                    style="
                                      border-collapse: separate;
                                      width: 100%;
                                      line-height: 100%;
                                    "
                                  >
                                    <tr>
                                      <td
                                        align="center"
                                        bgcolor="rgba(0, 0, 0, 0)"
                                        role="presentation"
                                        style="
                                          border: 4px solid #11cdef;
                                          border-radius: 3px;
                                          cursor: auto;
                                          mso-padding-alt: 10px 25px;
                                          background: rgba(0, 0, 0, 0);
                                        "
                                        valign="middle"
                                      >
                                        <a
                                          href="http://localhost:4200/${link}?email=${email}&nom=${nom}&prenom=${prenom}"
                                          style="
                                            display: inline-block;
                                            background: rgba(0, 0, 0, 0);
                                            color: #11cdef;
                                            font-family: 'Merriweather',
                                              'Georgia', 'Times New Roman',
                                              serif;
                                            font-size: 20px;
                                            font-weight: normal;
                                            line-height: 1.5;
                                            margin: 0;
                                            text-decoration: none;
                                            text-transform: none;
                                            padding: 10px 25px;
                                            mso-padding-alt: 0px;
                                            border-radius: 3px;
                                          "
                                        >
                                          <strong>S'inscrire</strong>
                                        </a>
                                      </td>
                                    </tr>
                                  </table>
                                </td>
                              </tr>
                              <tr>
                                <td
                                  style="font-size: 0px; word-break: break-word"
                                >
                                  <div style="height: 40px; line-height: 40px">
                                    &#8202;
                                  </div>
                                </td>
                              </tr>
                            </tbody>
                          </table>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </body>
</html>
